const fs = require('fs');

// TODO: Create a function that returns a license badge based on which license is passed in
// If there is no license, return an empty string
function renderLicenseBadge(license) {}

// TODO: Create a function that returns the license link
// If there is no license, return an empty string
function renderLicenseLink(license) {}

// TODO: Create a function that returns the license section of README
// If there is no license, return an empty string
function renderLicenseSection(license) {}

// TODO: Create a function to generate markdown for README
function generateMarkdown(data) {
  return `
  # ${data.title}
  ${licenseBadge}
  
  ## Table of Contents
  * [Description](#description)
  * [Installation](#installation)
  * [Usage](#usage)
  * [License](#license)
  * [Contributing](#contributing)
  * [Tests](#tests)
  * [Questions](#questions)
  
  <a name='description'></a>
  ## Description
  ${data.description}
  
  <a name='installation'></a>
  ## Installation
  ${data.installation}
  
  <a name='usage'></a>
  ## Usage
  ${data.usage}
  
  <a name='license'></a>
  ## License
  ${data.license}
  
  <a name='contributing'></a>
  ## Contributing
  ${data.contributing}
  
  <a name='tests'></a>
  ## Tests
  ${data.tests}
  
  <a name='questions'></a>
  ## Questions
  Please email ${data.questions} with any questions. 
  
  ### This README was generated by (https://github.com/bcassellius/readme-generator).
  `;
}

module.exports = { generateMarkdown };
